proxy-groups:
#add
- name: Porn
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - DIRECT
- name: Tiktok
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - DIRECT
- name: Instagram
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - DIRECT


rules:
#add
- RULE-SET,rule_porn,Porn
- RULE-SET,rule_nsfw,Porn
- RULE-SET,rule_tiktok,Tiktok
- RULE-SET,rule_instagram,Instagram

rule-providers:
  #replace
  rule_Sosmed:
    type: http
    behavior: classical
    path: "./rule_provider/rule_sosmed.yaml"
    url: https://raw.githubusercontent.com/valvatacea/cfa-config/main/rule_provider/rule_sosmed.yaml
    interval: 86400

  #add
  rule_tiktok:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_tiktok.yaml
    path: "./rule_provider/rule_tiktok.yaml"
    interval: 86400
  rule_porn:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_porn.yaml
    path: "./rule_provider/rule_porn.yaml"
    interval: 86400
  rule_nsfw:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_nsfw.yaml
    path: "./rule_provider/rule_nsfw.yaml"
    interval: 43200
